version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - PNPM_VERSION=7.1.9
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
